ALTER TABLE `Scan`
  MODIFY `assessment` ENUM(
    'NO_STRONG_WARNING_SIGNS',
    'INSUFFICIENT_EVIDENCE',
    'CAUTION',
    'SUSPICIOUS',
    'STRONG_SCAM_INDICATORS',
    'UNABLE_TO_ASSESS'
  ) NOT NULL;

ALTER TABLE `Scan`
  ADD COLUMN `deterministicAssessment` ENUM(
    'NO_STRONG_WARNING_SIGNS',
    'INSUFFICIENT_EVIDENCE',
    'CAUTION',
    'SUSPICIOUS',
    'STRONG_SCAM_INDICATORS',
    'UNABLE_TO_ASSESS'
  ) NULL,
  ADD COLUMN `retrievalEvidence` JSON NULL;
